#+BLOG: blog.datalab.es
#+CATEGORY: 
#+TAGS: 
#+DESCRIPTION: 
#+AUTHOR: Adolfo Antón Bravo
#+EMAIL: adolfo@medialab-prado.es
#+TITLE: Data Science Madrid for OpenStack
#+DATE: <2017-01-17 mar 16:00>
#+OPTIONS:  num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil toc:nil
#+LATEX_HEADER: \usepackage[spanish]{babel}
#+LATEX_HEADER: \addto\captionsenglish{\renewcommand{\contentsname}{{\'I}ndice}}
#+LATEX_HEADER: \maketitle
#+LATEX_HEADER: \renewcommand{\contentsname}{Índice}
#+OPTIONS: reveal_center:t reveal_progress:t reveal_history:nil reveal_control:t
#+OPTIONS: reveal_mathjax:t reveal_rolling_links:t reveal_keyboard:t reveal_overview:t num:nil
#+OPTIONS: reveal_width:1200 reveal_height:800
#+REVEAL_MARGIN: 0.1
#+REVEAL_MIN_SCALE: 0.5
#+REVEAL_MAX_SCALE: 2.5
#+REVEAL_TRANS: linear
#+REVEAL_THEME: sky
#+REVEAL_HLEVEL: 2
#+REVEAL_HEAD_PREAMBLE: <meta name="description" content="Data Science Madrid for OpenStack">
#+REVEAL_POSTAMBLE: <p> Creado por adolflow. </p>
#+REVEAL_PLUGINS: (highlight notes)
#+REVEAL_EXTRA_CSS: file:///home/flow/Documentos/software/reveal.js/css/reveal.css
#+REVEAL_ROOT: file:///home/flow/Documentos/software/reveal.js/

Los grupos [[https://www.meetup.com/es-ES/Data-Science-Madrid/][Data Science Madrid]] y [[https://www.meetup.com/es-ES/MAD-for-OpenStack/][Mad for OpenStack]] empiezan 2017 con una actividad conjunta. El miércoles 25 de enero, Daniel Mellado y Carlos Camacho de [[https://redhat.com][Redhat]] realizarán una introducción a [[https://openstack.org][Open Stack]] y /Big Data/, mientras que Inés Huertas de [[http://datatons.com][DataTons]] hará lo propio con /Data Science/ y /Big Data/.

Una de las pretensiones del laboratorio de datos [[https://github.com/medialab-prado/datalab][Datalab]] de Medialab-Prado para 2017 es el aprendizaje colectivo, la mezcla, remezcla y producción conjunta de actividades y contenidos relacionados con el mundo de los datos. En este primer evento de 2017 hemos propuesto a dos Meetup que intenten ver las conexiones de uno y otro para que aprendamos más y mejor.

#+CAPTION: Imagen de O'Reilly Conferences, Strata_SJ_2015_1937, Strata + hadoop World SJ 2015, CC
#+ATTR_HTML: :alt Imagen de O'Reilly Conferences, Strata_SJ_2015_1937, Strata + hadoop World SJ 2015, CC :title DataScience y OpenStack
https://farm8.staticflickr.com/7373/16400135150_31ff5f1b7e_z_d.jpg

Daniel y Carlos ofrecerán una breve presentación de [[https://openstack.org][OpenStack]] para quien no lo conozca para a continuación acercarnos a la integración de servicios para que soporte conjuntos de herramientas para el proceso de datos. El objetivo de la presentación es abordar el ecosistema OpenStack como entorno de gestión de aplicaciones en la nube de forma masiva y escalable. Para ello se centrarán en los componentes más importantes de OpenStack, los conceptos que hay detrás de [[http://docs.openstack.org/developer/sahara/][Sahara]] y su integración con el resto del ecosistema OpenStack

Por su parte, Inés propone aclarar dudas sobre el concepto /Data Science/ o /ciencia de datos/ y los términos relacionados como /datascientist/ o /científico de datos/, de dónde nace la necesidad de este perfil y qué aporta dentro de la industria del conocimiento. Además, explicará a qué retos se enfrenta a la hora de manejar diferentes volúmenes de datos, qué herramientas podemos usar para desarrollar analiticas en /Big Data/ y algunos ejemplos. 

* Agenda
Auditorio, de 19 a 20:30:
- 19:00, "Open Stack y Big Data" por Daniel Mellado y Carlos Camacho
  - Introducción a OpenStack
  - Algunos componentes
  - Hadoop
  - Sahara
- 19:30, "Data Science + Big Data " por Inés Huertas
- 20:00, charla y piscolabis


